services:
  db:
    image: postgres:16-alpine
    container_name: projeto-spotify-db
    environment:
      POSTGRES_DB: spotify_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: projeto-spotify-backend
    ports:
      - "5000:5000" # Porta da aplicação
      - "5005:5005" # Porta de depuração
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spotify_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_SECRET}
      - SPOTIFY_REDIRECT_URI=http://127.0.0.1:5000/api/auth/callback
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api
    ports:
      - "5173:80"
      - "9229:9229"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: